"relax": {"on":true,"bri":254,"ct":467,"alert":"none","effect":"none"}
"energize": {"on":true,"bri":203,"ct":156,"alert":"none","effect":"none"}
"reading": {"on":true,"bri":240,"ct":346,"alert":"none","effect":"none"}
"concentrate": {"on":true,"bri":219,"ct":231,"alert":"none","effect":"none"}
